import { defineSchema, defineTable } from 'convex/server';
import { v } from 'convex/values';

export default defineSchema({
  newsItems: defineTable({
    title: v.string(),
    url: v.string(),
    hnId: v.optional(v.string()),
    points: v.optional(v.number()),
    author: v.optional(v.string()),
    ageText: v.optional(v.string()), // e.g., "2 hours ago"
    source: v.string(), // e.g., "Hacker News"
    scrapedAt: v.number(), // Timestamp of when it was scraped
    summary: v.optional(v.string()), // Generated by Gemini
    processingState: v.optional(v.string()), // e.g., "summarized", "failed_summary"
  })
    .index('by_url', ['url']) // To quickly check for existing items by URL
    .index('by_hnId', ['hnId']) // To quickly check by Hacker News ID
    .index('by_scrapedAt', ['scrapedAt']), // For sorting by scrapedAt
});
