// Generated by Copilot
import { type ClassValue, clsx } from 'clsx';
import { twMerge } from 'tailwind-merge';

/**
 * A utility function that merges multiple class names with proper handling of Tailwind CSS conflicts
 * Generated by Copilot
 */
export function cn(...inputs: ClassValue[]): string {
  return twMerge(clsx(inputs));
}
