import { type ClassValue, clsx } from 'clsx'
import { twMerge } from 'tailwind-merge'
import dayjs from 'dayjs'
import relativeTime from 'dayjs/plugin/relativeTime'

// generated by shadcn
export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}

// created by chatgpt
export function isBase64Image(imageData: string) {
  const base64Regex = /^data:image\/(png|jpe?g|gif|webp);base64,/
  return base64Regex.test(imageData)
}

dayjs.extend(relativeTime)

export function formatDateString(date: Date) {
  const dateString = dayjs(date).fromNow(true)
  if(dateString.includes('year'))
    return dayjs(date).format('MMM D, YYYY')
  if(dateString.includes('month') || dateString.includes('day'))
    return dayjs(date).format('MMM D')
  return dayjs(date)
    .fromNow(true)
    .replace('a few seconds', '1minute')
    .replace('an', '1')
    .replace('a', '1')
    .replace('s', '')
    .replace('minute', 'm')
    .replace('hour', 'h')
    .replaceAll(' ', '')
}
