// Users and thoughts generated by copilot GPT 4o model

export const users = [
    {
        username: 'Aaron',
        email: 'Aaron@mail.com',
    },
    {
        username: 'Beth',
        email: 'Beth@mail.com',
    },
    {
        username: 'Charlie',
        email: 'Charlie@mail.com',
    },
    {
        username: 'Dan',
        email: 'Dan@mail.com',
    },
];

export const thoughts = [
    {
        thoughtText: 'Learning new frameworks is exciting!',
        username: 'Aaron',
    },
    {
        thoughtText: 'Coding is fun!',
        username: 'Aaron',
    },
    {
        thoughtText: 'I love TypeScript!',
        username: 'Beth',
    },
    {
        thoughtText: 'JavaScript is versatile.',
        username: 'Charlie',
    },
    {
        thoughtText: 'Debugging is like being a detective.',
        username: 'Dan',
    },
];