import { type ClassValue, clsx } from "clsx"
import { twMerge } from "tailwind-merge"

// Generated by snadcn
export function cn(...inputs: ClassValue[]) {
    return twMerge(clsx(inputs))
}

// Created by chatgpt
export function isBase64Image(imageData: string) {
    const base64RegExp = /^data:image\/(png|jpg|jpeg|gif|webp);base64,/;
    return base64RegExp.test(imageData);
}

// Created by chatgpt
export function formatDateString(dateString: string) {
    const options: Intl.DateTimeFormatOptions = {
        year: "numeric",
        month: "short",
        day: "numeric",
    };
    const date = new Date(dateString);
    const formattedDate = date.toLocaleDateString(undefined, options);
    const time = date.toLocaleTimeString([], {
        hour: "numeric",
        minute: "2-digit",
    });

    return `${time} - ${formattedDate}`;
}

// Created by chatgpt
export function formatThreadCount(count: number): string {
    if (count === 0) {
        return "No Threads";
    } else {
        const threadCount = count.toString().padStart(2, "0");
        const threadWord = count === 1? "Thread" : "Threads";

        return `${threadCount} ${threadWord}`;
    }
}
