// This file is generated by Gemini.
'use server';

/**
 * @fileOverview Generates a daily journal prompt for the user.
 *
 * - generateDailyPrompt - A function that generates a daily journal prompt.
 * - GenerateDailyPromptInput - The input type for the generateDailyPrompt function.
 * - GenerateDailyPromptOutput - The return type for the generateDailyPrompt function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateDailyPromptInputSchema = z.object({
  userMood: z
    .string()
    .describe('The current mood of the user, e.g. happy, sad, anxious.'),
});
export type GenerateDailyPromptInput = z.infer<typeof GenerateDailyPromptInputSchema>;

const GenerateDailyPromptOutputSchema = z.object({
  prompt: z.string().describe('A thought-provoking daily journal prompt.'),
});
export type GenerateDailyPromptOutput = z.infer<typeof GenerateDailyPromptOutputSchema>;

export async function generateDailyPrompt(input: GenerateDailyPromptInput): Promise<GenerateDailyPromptOutput> {
  return generateDailyPromptFlow(input);
}

const prompt = ai.definePrompt({
  name: 'dailyPromptGenerator',
  model: 'googleai/gemini-1.5-flash-latest', // Updated model specification
  input: {schema: GenerateDailyPromptInputSchema},
  output: {schema: GenerateDailyPromptOutputSchema},
  prompt: `You are a helpful assistant designed to generate daily journal prompts based on the user's current mood.

  Generate a thought-provoking and open-ended journal prompt that encourages reflection and self-awareness, tailored to the user's current mood.

  User Mood: {{{userMood}}}
  Prompt:`, 
});

const generateDailyPromptFlow = ai.defineFlow(
  {
    name: 'generateDailyPromptFlow',
    inputSchema: GenerateDailyPromptInputSchema,
    outputSchema: GenerateDailyPromptOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
