import type { NextApiRequest, NextApiResponse } from 'next';

const GEMINI_API_KEY = 'AIzaSyDne_AOfPQkM-dU-Aqtel-CM0WidhpMpRs';
const GEMINI_API_URL = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent?key=' + GEMINI_API_KEY;

function timeoutPromise<T>(promise: Promise<T>, ms: number, fallback: T): Promise<T> {
  return Promise.race([
    promise,
    new Promise<T>(resolve => setTimeout(() => resolve(fallback), ms))
  ]);
}

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { resumeText } = req.body;
  if (!resumeText || typeof resumeText !== 'string') {
    return res.status(400).json({ error: 'Missing or invalid resumeText' });
  }

  // Compose a prompt for Gemini
  const prompt = `You are an expert career coach and resume reviewer. Analyze the following resume text and provide:
- A summary of strengths
- Areas for improvement
- Actionable feedback
- A score from 1-100
- Any missing sections or red flags

Resume:
${resumeText}`;

  try {
    const geminiRes = await timeoutPromise(
      fetch(GEMINI_API_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          contents: [{ parts: [{ text: prompt }] }],
          generationConfig: { temperature: 0.4, maxOutputTokens: 1024 }
        })
      }),
      10000, // 10 seconds
      null
    );
    if (!geminiRes) {
      console.error('Gemini API timed out or did not respond');
      return res.status(200).json({ feedback: 'The AI is taking too long to respond. Please try again later or check your internet connection.' });
    }
    const data = await geminiRes.json();
    console.log('Gemini API response:', JSON.stringify(data));
    const feedback = data?.candidates?.[0]?.content?.parts?.[0]?.text || '';
    if (!feedback) {
      return res.status(200).json({ feedback: 'No feedback generated by Gemini. Please try again or use a different file.' });
    }
    res.status(200).json({ feedback });
  } catch (error) {
    console.error('Gemini API error:', error);
    res.status(200).json({ feedback: 'An error occurred while analyzing your resume. Please try again later.' });
  }
} 