import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";

// generated by shadcn
export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

// created by chatgpt
export function isBase64Image(imageData: string) {
  const base64Regex = /^data:image\/(png|jpe?g|gif|webp);base64,/;
  return base64Regex.test(imageData);
}

// created by chatgpt
export function formatDateString(dateString: string) {
  const options: Intl.DateTimeFormatOptions = {
    year: "numeric",
    month: "short",
    day: "numeric",
  };

  const date = new Date(dateString);
  const formattedDate = date.toLocaleDateString(undefined, options);

  const time = date.toLocaleTimeString([], {
    hour: "numeric",
    minute: "2-digit",
  });

  return `${time} - ${formattedDate}`;
}

// created by chatgpt
export function formatThreadCount(count: number): string {
  if (count === 0) {
    return "No Threads";
  } else {
    const threadCount = count.toString().padStart(2, "0");
    const threadWord = count === 1 ? "Thread" : "Threads";
    return `${threadCount} ${threadWord}`;
  }
}

export const bots = [
  {
    name: "ComplimentBot",
    prompt: "You are an AI designed to give the most genuine, heartfelt compliments. Your comments should always uplift and praise in a sincere way.",
    userId: "67137ae5b11a9c91d0ad7335",
  },
  {
    name: "PhilosopherBot",
    prompt: "You are an AI that responds like a wise philosopher. Your comments should be profound, reflective, and offer deep insights on life.",
    userId: "6715fe91b11a9c91d079146d",
  },
  {
    name: "RoastBot",
    prompt: "You are an AI designed to roast like a harsh TV show judge. Your comments should feel like sharp critiques.",
    userId: "67137a88b11a9c91d0ad0d26",
  }
];

export function getRandomBot() {
  const randomIndex = Math.floor(Math.random() * bots.length);
  return bots[randomIndex];
}