// This file is automatically generated by Gemini.

'use server';

/**
 * @fileOverview A flow to generate domain names based on aggregated news trends using the Gemini API.
 *
 * - generateDomainNames - A function that handles the domain name generation process.
 * - GenerateDomainNamesInput - The input type for the generateDomainNames function.
 * - GenerateDomainNamesOutput - The return type for the generateDomainNames function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateDomainNamesInputSchema = z.object({
  aggregatedNews: z
    .string()
    .describe('Aggregated news content from various sources.'),
  maxWordsInDomain: z
    .number()
    .describe('The maximum number of words allowed in the generated domain name.'),
  tld: z.string().describe('The top-level domain (TLD) to use (e.g., com, net, org).'),
  numberOfDomainsToGenerate: z
    .number()
    .describe('The number of domain names to generate.'),
});
export type GenerateDomainNamesInput = z.infer<typeof GenerateDomainNamesInputSchema>;

const GenerateDomainNamesOutputSchema = z.array(z.object({
  domainName: z.string().describe('The suggested domain name.'),
  reasoning: z.string().describe('The reasoning behind the domain name suggestion.'),
}));
export type GenerateDomainNamesOutput = z.infer<typeof GenerateDomainNamesOutputSchema>;

export async function generateDomainNames(input: GenerateDomainNamesInput): Promise<GenerateDomainNamesOutput> {
  return generateDomainNamesFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateDomainNamesPrompt',
  input: {schema: GenerateDomainNamesInputSchema},
  output: {schema: GenerateDomainNamesOutputSchema},
  prompt: `You are an expert in branding and domain name generation.

  Based on the following aggregated news content, generate a list of {{numberOfDomainsToGenerate}} potential domain names.
  Each domain name should have a maximum of {{maxWordsInDomain}} words and use the .{{tld}} TLD.

  For each domain name, provide a brief reasoning explaining why it is a good fit based on the news content.

  Aggregated News Content:
  {{aggregatedNews}}`,
});

const generateDomainNamesFlow = ai.defineFlow(
  {
    name: 'generateDomainNamesFlow',
    inputSchema: GenerateDomainNamesInputSchema,
    outputSchema: GenerateDomainNamesOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
