// This file is generated by Gemini, do not edit!
'use server';

/**
 * @fileOverview A service recommendation AI agent.
 *
 * - recommendService - A function that handles the service recommendation process.
 * - RecommendServiceInput - The input type for the recommendService function.
 * - RecommendServiceOutput - The return type for the recommendService function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const RecommendServiceInputSchema = z.object({
  problemDescription: z
    .string()
    .describe('A description of the home service issue in natural language.'),
});
export type RecommendServiceInput = z.infer<typeof RecommendServiceInputSchema>;

const RecommendServiceOutputSchema = z.object({
  serviceCategory: z.string().describe('The recommended service category.'),
  reasoning: z.string().describe('The reasoning behind the service category recommendation.'),
});
export type RecommendServiceOutput = z.infer<typeof RecommendServiceOutputSchema>;

export async function recommendService(input: RecommendServiceInput): Promise<RecommendServiceOutput> {
  return recommendServiceFlow(input);
}

const prompt = ai.definePrompt({
  name: 'recommendServicePrompt',
  input: {schema: RecommendServiceInputSchema},
  output: {schema: RecommendServiceOutputSchema},
  prompt: `You are an AI assistant designed to recommend the most appropriate service category for home service issues. Based on the user's description of their problem, you will determine the most relevant service category and explain your reasoning.

User's Problem Description: {{{problemDescription}}}

Consider these service categories:
- Plumbing
- Electrician
- Servant
- Cook
- Mechanic
- Others

Output the service category and your reasoning for recommending that category.
`,
});

const recommendServiceFlow = ai.defineFlow(
  {
    name: 'recommendServiceFlow',
    inputSchema: RecommendServiceInputSchema,
    outputSchema: RecommendServiceOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
