// Generated by Copilot
import { TickType } from '../enums/TickType';

/**
 * Represents a single option quote as returned by the Questrade API.
 *
 * @remarks
 * See: https://www.questrade.com/api/documentation/rest-operations/market-calls/markets-quotes-options
 */
export interface IOptionQuote {
    /** Underlying symbol. */
    underlying: string;
    /** Underlying symbol ID. */
    underlyingId: number;
    /** Option symbol. */
    symbol: string;
    /** Option symbol ID. */
    symbolId: number;
    /** Bid price. */
    bidPrice: number;
    /** Bid size. */
    bidSize: number;
    /** Ask price. */
    askPrice: number;
    /** Ask size. */
    askSize: number;
    /** Last trade price during trading hours. */
    lastTradePriceTrHrs: number;
    /** Last trade price. */
    lastTradePrice: number;
    /** Last trade size. */
    lastTradeSize: number;
    /** Last trade tick direction. */
    lastTradeTick: TickType;
    /** Last trade time (ISO 8601 format). */
    lastTradeTime: string;
    /** Trading volume. */
    volume: number;
    /** Opening price. */
    openPrice: number;
    /** High price. */
    highPrice: number;
    /** Low price. */
    lowPrice: number;
    /** Implied volatility. */
    volatility: number;
    /** Option delta. */
    delta: number;
    /** Option gamma. */
    gamma: number;
    /** Option theta. */
    theta: number;
    /** Option vega. */
    vega: number;
    /** Option rho. */
    rho: number;
    /** Open interest. */
    openInterest: number;
    /** Quote delay in seconds. */
    delay: number;
    /** Whether the option is currently halted. */
    isHalted: boolean;
    /** Volume weighted average price. */
    VWAP: number;
}

/**
 * Response object for GET markets/quotes/options containing an array of option quote records.
 */
export interface IGetOptionQuotesResponse {
    /** Array of option quote records. */
    optionQuotes: IOptionQuote[];
}
