export type CarMakerDTO = {
  id: string
  name: string
}

export type CarModelDTO = {
  modelId: string
  modelName: string
}

const Hyundai = {
  id: '1',
  name: 'Hyundai'
}

const Toyota = {
  id: '2',
  name: 'Toyota'
}

const VolksWagen = {
  id: '3',
  name: 'VolksWagen'
}

const Ford = {
  id: '4',
  name: 'Ford'
}

const MockedResponse: CarMakerDTO[] = [Hyundai, Toyota, VolksWagen, Ford]

// Data below generated by ChatGPT :)
const HundaiCarModels: CarModelDTO[] = [
  { modelId: '1', modelName: 'Elantra' },
  { modelId: '2', modelName: 'Sonata' },
  { modelId: '3', modelName: 'Tucson' },
  { modelId: '4', modelName: 'Santa Fe' }
]

const ToyotaCarModels: CarModelDTO[] = [
  { modelId: '1', modelName: 'Camry' },
  { modelId: '2', modelName: 'Corolla' },
  { modelId: '3', modelName: 'Highlander' },
  { modelId: '4', modelName: 'Rav4' }
]

const VWCarModels: CarModelDTO[] = [
  { modelId: '1', modelName: 'Golf' },
  { modelId: '2', modelName: 'Jetta' },
  { modelId: '3', modelName: 'Passat' },
  { modelId: '4', modelName: 'Tiguan' }
]

const FordCarModels: CarModelDTO[] = [
  { modelId: '1', modelName: 'Escape' },
  { modelId: '2', modelName: 'F-150' },
  { modelId: '3', modelName: 'Focus' },
  { modelId: '4', modelName: 'Mustang' }
]

const CarModelsByMakerId: Record<string, CarModelDTO[] | undefined> = {
  '1': HundaiCarModels,
  '2': ToyotaCarModels,
  '3': VWCarModels,
  '4': FordCarModels
}

export const fetchCarMakers = async () => {
  // API call would be here
  await new Promise(resolve => setTimeout(resolve, 1000))

  return MockedResponse
}

export const fetchCarModelsByMakerId = async (careMakerId: string) => {
  // API call would be here
  await new Promise(resolve => setTimeout(resolve, 1000))

  return CarModelsByMakerId[careMakerId] ?? []
}
