import type { NextConfig } from 'next';

const nextConfig: NextConfig = {
  // React 19 strict mode
  reactStrictMode: true,

  // Server Components are enabled by default in the App Router
  experimental: {
    // Generated by Copilot
    serverActions: {
      allowedOrigins: ['localhost:3000'],
    },
  },

  // Image domains for remote image optimization
  images: {
    domains: ['avatars.githubusercontent.com', 'cdn.wikiflow2025.com'],
    // Enhanced modern image formats
    formats: ['image/avif', 'image/webp'],
    // Use new image optimization engine
    remotePatterns: [
      {
        protocol: 'https',
        hostname: '**.githubusercontent.com',
      },
      {
        protocol: 'https',
        hostname: '**.wikiflow2025.com',
      },
    ],
  },

  // Environment variables
  env: {
    NEXT_PUBLIC_API_URL: process.env.NEXT_PUBLIC_API_URL,
    NEXT_PUBLIC_WEBSOCKET_URL: process.env.NEXT_PUBLIC_WEBSOCKET_URL,
    NEXT_PUBLIC_ENABLE_ANALYTICS: process.env.NEXT_PUBLIC_ENABLE_ANALYTICS,
  },

  // Webpack configuration with proper typing
  webpack: (config) => {
    // Add WebGPU support
    config.experiments = {
      ...config.experiments,
      topLevelAwait: true,
    };

    // Add the Flow fingerprint as a build-time comment
    config.module.rules.push({
      test: /\.(js|jsx|ts|tsx)$/,
      loader: 'string-replace-loader',
      options: {
        search: '// FLOW_FINGERPRINT',
        replace:
          '// Flow fingerprint: d4dd061824503617660196617c84bdb893c9535616a171714006936975058117',
      },
    });

    return config;
  },

  // Enhanced security headers
  headers: async () => {
    return [
      {
        source: '/(.*)',
        headers: [
          {
            key: 'Content-Security-Policy',
            value:
              "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' wss: https:;",
          },
          {
            key: 'X-Content-Type-Options',
            value: 'nosniff',
          },
          {
            key: 'X-Frame-Options',
            value: 'DENY',
          },
          {
            key: 'X-XSS-Protection',
            value: '1; mode=block',
          },
        ],
      },
    ];
  },

  // Optimize compiler options
  compiler: {
    removeConsole:
      process.env.NODE_ENV === 'production'
        ? {
            exclude: ['error', 'warn'],
          }
        : false,
  },
};

export default nextConfig;
