import { gita_ch01 } from './gita_ch01';
import { gita_ch02 } from './gita_ch02';
import { gita_ch03 } from './gita_ch03';
import { gita_ch04 } from './gita_ch04';
import { gita_ch05 } from './gita_ch05';
import { gita_ch06 } from './gita_ch06';
import { gita_ch07 } from './gita_ch07';
import { gita_ch08 } from './gita_ch08';
import { gita_ch09 } from './gita_ch09';
import { gita_ch10 } from './gita_ch10';
import { gita_ch11 } from './gita_ch11';
import { gita_ch12 } from './gita_ch12';
import { gita_ch13 } from './gita_ch13';
import { gita_ch14 } from './gita_ch14';
import { gita_ch15 } from './gita_ch15';
import { gita_ch16 } from './gita_ch16';
import { gita_ch17 } from './gita_ch17';
import { gita_ch18 } from './gita_ch18';
import { chapters } from './gita_chapter_titles';

/**
 * Represents a verse from the Bhagavad Gita.
 */
interface VerseBase {
  /**
   * The chapter number of the verse.
   */
  chapter: number;
  /**
   * The verse number within the chapter.
   */
  verse: number;
}

export interface Verse extends VerseBase {
  /**
   * The text of the verse in Sanskrit.
   */
  text: string;
  importance: number;
  translation: string;
  translation_jp: string;
}

export interface VerseWithTranslation extends VerseBase {
  importance: number;
  translation: string;
  translation_jp: string;
}

export interface Chapter {
  chapter: number;
  title: string;
  japaneseTitle: string;
};

/**
 * Asynchronously retrieves a random verse from the Bhagavad Gita.
 *
 * @returns A promise that resolves to a Verse object containing the chapter, verse number, and text.
 */
export async function getRandomVerse(): Promise<Verse> {
  const verses: Verse[] = verseArray;

  // Randomly select a verse from the array
  const randomIndex = Math.floor(Math.random() * verses.length);
  return verses[randomIndex];
}

export async function getFirstVerse(): Promise<Verse> {
  return verseArray[0];
}

export async function getAllVerses(): Promise<Verse[]> {
  return getVerses();
}

export async function getChapterTitles(): Promise<Chapter[]> {
  return chapters;
}

/**
 * Asynchronously retrieves a list of verses from the Bhagavad Gita.
 *
 * @returns A promise that resolves to an array of Verse objects.
 */
async function getVerses(): Promise<Verse[]> {
  // Replace this with an actual implementation that fetches the verses.
  return verseArray;
}

export const footer_Message = 'All Translations and Commentaries of Verses are Generated by Gemini AI.';
export const footer_Message_jp = '全ての訳や節の解説はGemini AIによって生成されたものです。';

const verseArray = [
  ...gita_ch01,
  ...gita_ch02,
  ...gita_ch03,
  ...gita_ch04,
  ...gita_ch05,
  ...gita_ch06,
  ...gita_ch07,
  ...gita_ch08,
  ...gita_ch09,
  ...gita_ch10,
  ...gita_ch11,
  ...gita_ch12,
  ...gita_ch13,
  ...gita_ch14,
  ...gita_ch15,
  ...gita_ch16,
  ...gita_ch17,
  ...gita_ch18,
];
