import { Planet, TileType, AIStory, PlanetType } from '../types/universe';
import { GeminiConfig } from '../config/gemini.config';

interface GeminiResponse {
  candidates: Array<{
    content: {
      parts: Array<{
        text: string;
      }>;
    };
  }>;
}

const TILE_DESCRIPTIONS: Record<TileType, string> = {
  mountain: 'pics imposants qui percent le ciel',
  plain: 'vastes prairies vallonnées',
  forest: 'bois anciens remplis de secrets',
  ocean: 'eaux infinies cachant des mystères en contrebas',
  desert: 'étendues désolées où des civilisations prospéraient autrefois',
  ruins: 'vestiges croulants de civilisations oubliées',
  city: 'métropole animée d\'êtres avancés',
  volcano: 'pics volcaniques actifs avec des rivières de roche en fusion',
  mystic_jungle: 'forêts éthérées où la réalité se déforme',
  toxic_swamp: 'marais empoisonnés aux propriétés surnaturelles',
  crystal_land: 'formations cristallines qui chantent avec une énergie d\'un autre monde',
};

const PLANET_TYPE_CONTEXTS: Record<PlanetType, string> = {
  inhabited: 'un monde prospère avec des civilisations diverses, des cultures riches et des mythologies complexes',
  dead: 'un monde désolé portant les cicatrices d\'anciennes catastrophes et de civilisations oubliées',
  mystical: 'un monde où la magie et le mystère imprègnent chaque aspect de l\'existence',
  technological: 'un monde avancé où la technologie a transcendé les frontières normales',
};

function generatePrompt(planet: Planet, tileContext?: { x: number; y: number; type: TileType }): string {
  const planetContext = PLANET_TYPE_CONTEXTS[planet.type]; // Already French from previous step
  const tileDescription = tileContext ? TILE_DESCRIPTIONS[tileContext.type] : ''; // Already French from previous step
  
  let prompt = `Vous êtes un oracle mystique révélant les secrets de mondes lointains. `; // Translated
  
  if (tileContext) {
    prompt += `Sur la planète ${planet.name}, ${planetContext}, il existe une région de ${tileDescription}. `; // Structure maintained, variables are French content
  } else {
    prompt += `La planète ${planet.name} est ${planetContext}. `; // Structure maintained
  }

  switch (planet.type) {
    case 'inhabited':
      prompt += `Parlez-moi de la fascinante civilisation qui habite ce lieu. Décrivez leurs croyances, leurs coutumes, leurs plus grandes réalisations et les légendes qu'ils racontent sur leurs origines. Qu'est-ce qui rend leur culture unique dans le cosmos ?`; // Translated
      break;
    case 'dead':
      prompt += `Ce monde n'a pas toujours été silencieux. Racontez-moi l'histoire tragique de ce qui s'est passé ici. Quelle civilisation a prospéré autrefois ? Quelle catastrophe les a frappés ? Quels signes obsédants de leur existence restent visibles à ce jour ?`; // Translated
      break;
    case 'mystical':
      prompt += `Ce royaume pulse d'une énergie d'un autre monde. Décrivez les forces mystiques qui façonnent cette terre, la magie ancienne qui la traverse et les phénomènes surnaturels qui s'y manifestent. Quels secrets les esprits murmurent-ils ?`; // Translated
      break;
    case 'technological':
      prompt += `Ce monde a transcendé la compréhension conventionnelle grâce à la technologie. Décrivez les incroyables merveilles technologiques, les consciences IA qui ont pu évoluer, et les intelligences posthumaines ou extraterrestres qui façonnent la réalité ici.`; // Translated
      break;
  }

  prompt += ` Écrivez un récit atmosphérique et captivant de 150-200 mots qui capture l'essence du mystère et de la merveille de ce monde.`; // Translated
  prompt += ` Raconte cette histoire en français.`; // This line will be reviewed in the next step, kept for now.

  return prompt;
}

export class IAStoryGenerator {
  private static async makeRequest(prompt: string): Promise<string> {
    if (!GeminiConfig.isConfigured()) {
      throw new Error('Gemini API key not configured. Please set your API key in the settings.');
    }

    const requestBody = {
      contents: [{
        parts: [{
          text: prompt
        }]
      }],
      generationConfig: {
        temperature: 0.8,
        topK: 40,
        topP: 0.95,
        maxOutputTokens: 300,
      }
    };

    const response = await fetch(`${GeminiConfig.endpoint}?key=${GeminiConfig.apiKey}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(requestBody),
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      throw new Error(`Gemini API error: ${response.status} - ${errorData.error?.message || response.statusText}`);
    }

    const data: GeminiResponse = await response.json();
    
    if (!data.candidates || data.candidates.length === 0) {
      throw new Error('No story generated by Gemini API');
    }

    return data.candidates[0].content.parts[0].text;
  }

  static async generatePlanetStory(planet: Planet): Promise<AIStory> {
    const prompt = generatePrompt(planet);
    const content = await this.makeRequest(prompt);

    return {
      id: crypto.randomUUID(),
      planetId: planet.id,
      content: content.trim(),
      timestamp: Date.now(),
    };
  }

  static async generateTileStory(planet: Planet, tileX: number, tileY: number): Promise<AIStory> {
    const tile = planet.tiles.find(t => t.x === tileX && t.y === tileY);
    if (!tile) {
      throw new Error('Tile not found');
    }

    const tileContext = { x: tileX, y: tileY, type: tile.type };
    const prompt = generatePrompt(planet, tileContext);
    const content = await this.makeRequest(prompt);

    return {
      id: crypto.randomUUID(),
      planetId: planet.id,
      content: content.trim(),
      timestamp: Date.now(),
      tileContext,
    };
  }
}