import { config, validateConfig } from "./envConfig";

interface GeminiRequest {
  contents: {
    parts: {
      text: string;
    }[];
  }[];
}

interface GeminiResponse {
  candidates: {
    content: {
      parts: {
        text: string;
      }[];
    };
  }[];
}

export interface GenerateContentParams {
  prompt: string;
  format: "poem" | "essay";
  tone: string;
  style: string;
  wordCount: number;
  imageFile?: File;
}

export const generateContent = async (
  params: GenerateContentParams,
): Promise<string> => {
  try {
    validateConfig();

    const { prompt, format, tone, style, wordCount, imageFile } = params;

    // Create a detailed prompt for Gemini
    let detailedPrompt = `Generate a ${format} about "${prompt}" with the following specifications:
- Format: ${format}
- Tone: ${tone}
- Style: ${style}
- Target word count: approximately ${wordCount} words

Please create a well-structured ${format} that captures the essence of "${prompt}" while maintaining the ${tone} tone and ${style} style. ${format === "poem" ? "Use appropriate poetic devices and structure." : "Ensure proper essay structure with introduction, body, and conclusion."}`;

    // Prepare the request parts
    const parts: any[] = [];

    // Add image if provided
    if (imageFile) {
      const imageBase64 = await convertImageToBase64(imageFile);
      const mimeType = imageFile.type;

      parts.push({
        inline_data: {
          mime_type: mimeType,
          data: imageBase64,
        },
      });

      detailedPrompt = `Based on the provided image, generate a ${format} with the following specifications:
- Format: ${format}
- Tone: ${tone}
- Style: ${style}
- Target word count: approximately ${wordCount} words
- Additional context: ${prompt}

Analyze the image carefully and create a ${format} that describes, interprets, or is inspired by what you see in the image. ${format === "poem" ? "Use appropriate poetic devices and structure to capture the visual elements, emotions, or story suggested by the image." : "Ensure proper essay structure with introduction, body, and conclusion while discussing the visual elements, themes, or narrative suggested by the image."}`;
    }

    parts.push({
      text: detailedPrompt,
    });

    const requestBody: GeminiRequest = {
      contents: [
        {
          parts,
        },
      ],
    };

    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${config.geminiApiKey}`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(requestBody),
      },
    );

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`Gemini API error: ${response.status} - ${errorText}`);
    }

    const data: GeminiResponse = await response.json();

    if (!data.candidates || data.candidates.length === 0) {
      throw new Error("No content generated by Gemini API");
    }

    const generatedText = data.candidates[0].content.parts[0].text;
    return generatedText;
  } catch (error) {
    console.error("Error generating content:", error);
    throw error;
  }
};

// Helper function to convert image to base64
const convertImageToBase64 = (file: File): Promise<string> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => {
      const result = reader.result as string;
      // Remove the data URL prefix (e.g., "data:image/jpeg;base64,")
      const base64 = result.split(",")[1];
      resolve(base64);
    };
    reader.onerror = reject;
    reader.readAsDataURL(file);
  });
};
