import { GoogleGenerativeAI } from "@google/generative-ai";
import { NextResponse } from "next/server"; // If you're using Next.js or adapt to your framework
import nodemailer from "nodemailer";
import { marked } from "marked";

export async function POST(request: Request) {
  try {
    // Parse the incoming JSON request body
    const { message } = await request.json();

    // Validate message input
    if (!message) {
      return new NextResponse("Message is required", { status: 400 });
    }

    // Initialize Google Gemini AI
    const genAI = new GoogleGenerativeAI(process.env.API_KEY || "");
    const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });

    // Construct the prompt for Gemini to fetch advice on reducing water consumption
    const prompt = `The user has reported high water consumption and water flow. Provide detailed advice on reducing water usage and flow in daily activities, including tips on household water conservation, efficient usage in gardens, and other relevant suggestions to improve water flow management.`;

    // Generate content from Gemini AI
    const generatedContent = await model.generateContent([{ text: prompt }]);

    // The response text generated by Gemini
    const geminiResponse = generatedContent.response.text();

    // Convert the Gemini response from Markdown to HTML
    const geminiResponseHtml = marked(geminiResponse);

    // Create a Gmail transporter using Nodemailer
    const transporter = nodemailer.createTransport({
      service: "gmail",
      auth: {
        user: process.env.EMAIL, // Gmail address for sending
        pass: process.env.PASSWORD, // Gmail app password or regular password (if 2FA is disabled)
      },
    });

    // Email content with HTML and styles, including the generated Gemini response
    const mailOptions = {
      from: process.env.EMAIL, // Sender email (must be the same as the auth user)
      to: "fernando.jport@gmail.com", // Recipient email address
      subject: "High Water Consumption & Flow Alert: Tips to Conserve", // Updated subject
      html: `
        <html>
          <head>
            <style>
              body {
                font-family: Arial, sans-serif;
                background-color: #f4f4f9;
                margin: 0;
                padding: 0;
              }
              .email-container {
                width: 80%;
                max-width: 600px;
                margin: 20px auto;
                background-color: white;
                padding: 8px;
                border-radius: 8px;
                box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
              }
              .email-header {
                text-align: center;
                background-color: #e34f53;
                color: white;
                padding: 15px;
                border-radius: 8px 8px 0 0;
              }
              .email-header h1 {
                margin: 0;
                font-size: 24px;
              }
              .email-content {
                padding: 20px;
                line-height: 1.6;
                font-size: 16px;
              }
              .email-content h2 {
                color: #e34f53;
              }
              .tip {
                margin-bottom: 15px;
                background-color: #f9f9f9;
                padding: 10px;
                border-left: 5px solid #e34f53;
                box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
              }
              .tip strong {
                font-weight: bold;
              }
              .footer {
                text-align: center;
                margin-top: 20px;
                font-size: 14px;
                color: #888;
              }
            </style>
          </head>
          <body>
            <div class="email-container">
              <div class="email-header">
                <h1>High Water Consumption & Flow Alert</h1>
              </div>
              <div class="email-content">
                <p>Dear User,</p>
                <p>We've noticed your reported high water consumption and flow. Addressing these issues can help reduce your environmental impact and save resources. Here are some valuable tips to reduce water usage and manage flow effectively:</p>
                
                <!-- Gemini-generated advice section -->
                <div class="tip">
                  <h2>AI-Generated Water Conservation Advice</h2>
                  <p>${geminiResponseHtml}</p>
                </div>

                <p>By implementing these strategies, you'll be able to conserve water, lower your usage, and make a positive impact on the environment.</p>
                <p>For further assistance or additional tips, feel free to reach out. Together, we can work towards more sustainable water usage.</p>
              </div>
              <div class="footer">
                <p>Thank you for your commitment to sustainability.</p>
                <p>Best regards,</p>
                <p>Your Water Conservation Team</p>
              </div>
            </div>
          </body>
        </html>
      `,
    };

    // Send the email via Nodemailer
    await transporter.sendMail(mailOptions);

    // Return a success response
    return new NextResponse(
      JSON.stringify({
        status: "success",
        message: "Email sent successfully with tips on reducing water consumption!",
      }),
      {
        status: 200,
        headers: { "Content-Type": "application/json" },
      }
    );
  } catch (error) {
    console.error("Error processing request:", error);
    return new NextResponse(
      JSON.stringify({ error: "Error processing the request." }),
      { status: 500, headers: { "Content-Type": "application/json" } }
    );
  }
}
