import {
  Injectable,
  InternalServerErrorException,
  NotFoundException,
} from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";
import { Repository } from "typeorm";
import { CatEntity } from "./entities/cat.entity";
import { CreateCatDto } from "./dto/create-cat.dto";
import { UpdateCatDto } from "./dto/update-cat.dto";

/**
 * Service responsible for managing cat operations
 * Provides methods for CRUD operations on cat data
 */
@Injectable()
export class CatsService {
  constructor(
    @InjectRepository(CatEntity)
    private readonly catsRepository: Repository<CatEntity>
  ) {}

  /**
   * Creates a new cat and adds it to the database
   * @param createCatDto - The cat data transfer object containing the cat information
   * @returns The created cat entity
   */
  async create(createCatDto: CreateCatDto): Promise<CatEntity> {
    try {
      const cat = this.catsRepository.create(createCatDto);
      return await this.catsRepository.save(cat);
    } catch (error) {
      throw new InternalServerErrorException("Failed to create cat");
    }
  }

  /**
   * Retrieves all cats from the database
   * @returns An array of all cat entities
   */
  async findAll(): Promise<CatEntity[]> {
    try {
      return await this.catsRepository.find();
    } catch (error) {
      throw new InternalServerErrorException("Failed to retrieve cats");
    }
  }

  /**
   * Finds a cat by its ID
   * @param id - The ID of the cat to find
   * @returns The found cat entity
   * @throws NotFoundException if the cat is not found
   */
  async findOne(id: number): Promise<CatEntity> {
    try {
      const cat = await this.catsRepository.findOneBy({ id });
      if (!cat) {
        throw new NotFoundException(`Cat with ID ${id} not found`);
      }
      return cat;
    } catch (error) {
      if (error instanceof NotFoundException) {
        throw error;
      }
      throw new InternalServerErrorException(
        `Failed to find cat with ID ${id}`
      );
    }
  }

  /**
   * Finds a cat by its ID (alias for findOne)
   * @param id - The ID of the cat to find
   * @returns The found cat entity
   * @throws NotFoundException if the cat is not found
   *
   * Generated by Copilot @Jeremy
   */
  async findById(id: number): Promise<CatEntity> {
    try {
      const cat = await this.catsRepository.findOneBy({ id });
      if (!cat) {
        throw new NotFoundException(`Cat with ID ${id} not found`);
      }
      return cat;
    } catch (error) {
      if (error instanceof NotFoundException) {
        throw error;
      }
      throw new InternalServerErrorException(
        `Failed to find cat with ID ${id}`
      );
    }
  }

  /**
   * Finds a cat by its name
   * @param name - The name of the cat to find
   * @returns The found cat entity
   * @throws NotFoundException if the cat is not found
   */
  async findByName(name: string): Promise<CatEntity> {
    try {
      const cat = await this.catsRepository.findOneBy({ name });
      if (!cat) {
        throw new NotFoundException(`Cat with name ${name} not found`);
      }
      return cat;
    } catch (error) {
      if (error instanceof NotFoundException) {
        throw error;
      }
      throw new InternalServerErrorException(
        `Failed to find cat with name ${name}`
      );
    }
  }

  /**
   * Updates a cat with the provided data
   * @param id - The ID of the cat to update
   * @param updateCatDto - The data to update the cat with
   * @returns The updated cat entity
   * @throws NotFoundException if the cat is not found
   */
  async update(id: number, updateCatDto: UpdateCatDto): Promise<CatEntity> {
    try {
      const cat = await this.findOne(id);

      // Apply updates to the cat entity
      Object.assign(cat, {
        ...updateCatDto,
        updatedAt: new Date(),
      });

      return await this.catsRepository.save(cat);
    } catch (error) {
      if (error instanceof NotFoundException) {
        throw error;
      }
      throw new InternalServerErrorException(
        `Failed to update cat with ID ${id}`
      );
    }
  }

  /**
   * Removes a cat from the database
   * @param id - The ID of the cat to remove
   * @returns The deleted cat entity
   * @throws NotFoundException if the cat is not found
   */
  async remove(id: number): Promise<CatEntity> {
    try {
      const cat = await this.findOne(id);
      return await this.catsRepository.remove(cat);
    } catch (error) {
      if (error instanceof NotFoundException) {
        throw error;
      }
      throw new InternalServerErrorException(
        `Failed to delete cat with ID ${id}`
      );
    }
  }
}
