// Generated by Copilot
import forms from '@tailwindcss/forms';
import typography from '@tailwindcss/typography';
import type { Config } from 'tailwindcss';

// Custom plugin with error handling and better typing
const customBaseStyles = {
  handler: ({ addBase, theme }: { addBase: Function; theme: Function }) => {
    try {
      addBase({
        html: { fontFamily: theme('fontFamily.sans') },
        'code, pre': { fontFamily: theme('fontFamily.mono') },
        'h1, h2, h3, h4, h5, h6': { fontFamily: theme('fontFamily.display') },
      });
    } catch (error) {
      console.error('Error in Tailwind plugin:', error);
    }
  },
};

// Add a custom utilities plugin to generate specific utility classes that are used frequently
const customUtilities = {
  handler: ({ addUtilities }: { addUtilities: Function }) => {
    try {
      const newUtilities = {
        '.text-glow': {
          'text-shadow':
            '0 2px 24px rgba(124, 242, 236, 0.56), 0 1px 2px rgba(0, 0, 0, 0.44)',
        },
        '.shadow-glow': {
          'box-shadow': '0 0 15px 5px rgba(0, 255, 255, 0.3)',
        },
        '.gradient-text': {
          'background-clip': 'text',
          '-webkit-background-clip': 'text',
          color: 'transparent',
          'background-image':
            'linear-gradient(92deg, #32ffe7 60%, #ffe567 100%)',
        },
        '.scrollbar-hide': {
          '-ms-overflow-style': 'none',
          'scrollbar-width': 'none',
          '&::-webkit-scrollbar': {
            display: 'none',
          },
        },
      };
      addUtilities(newUtilities);
    } catch (error) {
      console.error('Error in custom utilities plugin:', error);
    }
  },
};

const config: Config = {
  content: [
    './src/app/**/*.{js,ts,jsx,tsx}',
    './src/pages/**/*.{js,ts,jsx,tsx}',
    './src/components/**/*.{js,ts,jsx,tsx}',
  ],
  future: {
    hoverOnlyWhenSupported: true, // Performance optimization for mobile
    disableColorOpacityUtilitiesByDefault: false, // Keep color opacity utilities for backward compatibility
  },
  // Add safelist for dynamically generated classes that need to be included
  safelist: [
    'text-accent',
    'bg-accent',
    'shadow-neon',
    'shadow-neon-green',
    'shadow-neon-pink',
    'shadow-champion',
    'text-glow',
    'gradient-text',
    // Animation classes that might be added dynamically
    'animate-pulse-slow',
    'animate-glow',
    'animate-float',
  ],
  theme: {
    // Use consistent color definitions across all config files
    colors: {
      // Base colors
      white: '#ffffff',
      black: '#000000',
      transparent: 'transparent',
      current: 'currentColor',

      // Standard Tailwind gray colors
      gray: {
        50: '#f9fafb',
        100: '#f3f4f6',
        200: '#e5e7eb',
        300: '#d1d5db',
        400: '#9ca3af',
        500: '#6b7280',
        600: '#4b5563',
        700: '#374151',
        800: '#1f2937',
        900: '#111827',
        950: '#030712',
      },
      // WikiFlow 2025 brand colors
      primary: {
        DEFAULT: '#0F172A', // Deep blue
        50: '#f8fafc',
        100: '#f1f5f9',
        200: '#e2e8f0',
        300: '#cbd5e1',
        400: '#94a3b8',
        500: '#64748b',
        600: '#475569',
        700: '#334155',
        800: '#1e293b',
        900: '#0f172a',
        950: '#020617',
      },
      accent: {
        DEFAULT: '#FFD700', // Gold
        light: '#FFEA80',
        dark: '#B7950B',
      },
      neon: {
        DEFAULT: '#00FFFF', // Cyan
        green: '#39FF14',
        pink: '#FF10F0',
        blue: '#0099FF',
      },
      champion: {
        DEFAULT: '#9333EA', // Purple
        light: '#C084FC',
        dark: '#6B21A8',
      },
    },
    screens: {
      xs: '480px',
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
      '2xl': '1536px',
      short: { raw: '(max-height: 768px)' }, // For height-based media queries
      tall: { raw: '(min-height: 769px)' },
      dark: { raw: '(prefers-color-scheme: dark)' }, // For dark mode media queries
    },
    extend: {
      fontFamily: {
        sans: ['var(--font-inter)', 'ui-sans-serif', 'system-ui'],
        mono: ['var(--font-fira-code)', 'ui-monospace', 'monospace'],
        display: ['var(--font-orbitron)', 'ui-sans-serif', 'system-ui'],
      },
      boxShadow: {
        neon: '0 0 5px theme(colors.neon.DEFAULT), 0 0 20px theme(colors.neon.DEFAULT)',
        'neon-green':
          '0 0 5px theme(colors.neon.green), 0 0 20px theme(colors.neon.green)',
        'neon-pink':
          '0 0 5px theme(colors.neon.pink), 0 0 20px theme(colors.neon.pink)',
      },
      animation: {
        'pulse-slow': 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        glow: 'glow 2s ease-in-out infinite alternate',
        float: 'float 6s ease-in-out infinite',
      },
      keyframes: {
        glow: {
          '0%': { boxShadow: '0 0 5px theme(colors.neon.DEFAULT)' },
          '100%': {
            boxShadow:
              '0 0 20px theme(colors.neon.DEFAULT), 0 0 30px theme(colors.neon.DEFAULT)',
          },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
      },
      backdropBlur: {
        xs: '2px',
      },
      spacing: {
        '4.5': '1.125rem',
        '13': '3.25rem',
        '15': '3.75rem',
        '128': '32rem',
        '144': '36rem',
      },
      // Add z-index values for better layering control
      zIndex: {
        '0': '0',
        '1': '1',
        '2': '2',
        '3': '3',
        '4': '4',
        '5': '5',
        '10': '10',
        '20': '20',
        '30': '30',
        '40': '40',
        '50': '50',
        '75': '75',
        '100': '100',
        auto: 'auto',
      },
      aspectRatio: {
        portrait: '3/4',
        landscape: '4/3',
        square: '1/1',
        video: '16/9',
      },
    },
  },
  // Enable JIT mode and other optimizations
  corePlugins: {
    // Disable features you don't use to reduce bundle size
    container: false, // Enable if you use Tailwind's container
    objectFit: false, // Modern browsers support this natively; use CSS directly
    objectPosition: false, // Modern browsers support this natively; use CSS directly
    filter: true, // Keeps filter utilities, used for glow effects
    backdropFilter: true, // Keeps backdrop filter, used for glass effects
  },
  plugins: [
    forms,
    typography,
    customBaseStyles.handler,
    customUtilities.handler,
  ],
} satisfies Config;

export default config;
