import { UIFormattedDailyFoodItem } from './models';

// ? Note: These are generated with ChatGPT,
// ? just used to populate and test the table/UI
const mockBreakfast: UIFormattedDailyFoodItem[] = [
  {
    name: 'Smoothie with Protein Powder',
    meal_type: 'breakfast',
    calories: '400 cal',
    carbs: '60g',
    fat: '5g',
    protein: '25g',
    sodium: '300mg',
    sugar: '35g',
  },
  {
    name: 'Oatmeal with Bananas',
    meal_type: 'breakfast',
    calories: '300 cal',
    carbs: '45g',
    fat: '5g',
    protein: '10g',
    sodium: '200mg',
    sugar: '15g',
  },
  {
    name: 'Greek Yogurt',
    meal_type: 'breakfast',
    calories: '100 cal',
    carbs: '18g',
    fat: '7g',
    protein: '14g',
    sodium: '50mg',
    sugar: '15g',
  },
  {
    name: 'Avocado Toast',
    meal_type: 'breakfast',
    calories: '350 cal',
    carbs: '40g',
    fat: '15g',
    protein: '12g',
    sodium: '250mg',
    sugar: '3g',
  },
  {
    name: 'Scrambled Eggs with Whole Wheat Toast',
    meal_type: 'breakfast',
    calories: '400 cal',
    carbs: '35g',
    fat: '18g',
    protein: '20g',
    sodium: '300mg',
    sugar: '2g',
  },
  {
    name: 'Greek Yogurt with Honey and Almonds',
    meal_type: 'breakfast',
    calories: '280 cal',
    carbs: '25g',
    fat: '8g',
    protein: '18g',
    sodium: '150mg',
    sugar: '12g',
  },
  {
    name: 'Oatmeal with Blueberries and Chia Seeds',
    meal_type: 'breakfast',
    calories: '320 cal',
    carbs: '45g',
    fat: '6g',
    protein: '10g',
    sodium: '200mg',
    sugar: '10g',
  },
];
const mockLunch: UIFormattedDailyFoodItem[] = [
  {
    name: 'Chicken Wrap with Veggies',
    meal_type: 'lunch',
    calories: '550 cal',
    carbs: '50g',
    fat: '15g',
    protein: '35g',
    sodium: '850mg',
    sugar: '4g',
  },
  {
    name: 'Turkey Sandwich',
    meal_type: 'lunch',
    calories: '500 cal',
    carbs: '55g',
    fat: '10g',
    protein: '30g',
    sodium: '900mg',
    sugar: '4g',
  },
  {
    name: 'Grilled Chicken Salad',
    meal_type: 'lunch',
    calories: '450 cal',
    carbs: '30g',
    fat: '20g',
    protein: '40g',
    sodium: '700mg',
    sugar: '5g',
  },
  {
    name: 'Turkey and Cheese Wrap',
    meal_type: 'lunch',
    calories: '480 cal',
    carbs: '50g',
    fat: '12g',
    protein: '35g',
    sodium: '900mg',
    sugar: '6g',
  },
  {
    name: 'Quinoa and Black Bean Bowl',
    meal_type: 'lunch',
    calories: '500 cal',
    carbs: '65g',
    fat: '10g',
    protein: '25g',
    sodium: '600mg',
    sugar: '4g',
  },
  {
    name: 'Tofu Stir-fry with Brown Rice',
    meal_type: 'lunch',
    calories: '520 cal',
    carbs: '70g',
    fat: '14g',
    protein: '30g',
    sodium: '850mg',
    sugar: '3g',
  },
  {
    name: 'Chicken Caesar Salad',
    meal_type: 'lunch',
    calories: '450 cal',
    carbs: '30g',
    fat: '20g',
    protein: '35g',
    sodium: '800mg',
    sugar: '5g',
  },
];
const mockDinner: UIFormattedDailyFoodItem[] = [
  {
    name: 'Spaghetti with Meatballs',
    meal_type: 'dinner',
    calories: '650 cal',
    carbs: '70g',
    fat: '20g',
    protein: '35g',
    sodium: '1000mg',
    sugar: '6g',
  },
  {
    name: 'Baked Salmon with Asparagus',
    meal_type: 'dinner',
    calories: '600 cal',
    carbs: '35g',
    fat: '25g',
    protein: '50g',
    sodium: '500mg',
    sugar: '2g',
  },
  {
    name: 'Spaghetti with Marinara Sauce',
    meal_type: 'dinner',
    calories: '550 cal',
    carbs: '75g',
    fat: '10g',
    protein: '20g',
    sodium: '800mg',
    sugar: '6g',
  },
  {
    name: 'Beef and Broccoli Stir-fry',
    meal_type: 'dinner',
    calories: '650 cal',
    carbs: '50g',
    fat: '20g',
    protein: '45g',
    sodium: '1000mg',
    sugar: '5g',
  },
  {
    name: 'Vegetable Curry with Lentils',
    meal_type: 'dinner',
    calories: '590 cal',
    carbs: '80g',
    fat: '12g',
    protein: '30g',
    sodium: '750mg',
    sugar: '8g',
  },
  {
    name: 'Grilled Salmon with Quinoa',
    meal_type: 'dinner',
    calories: '600 cal',
    carbs: '40g',
    fat: '25g',
    protein: '50g',
    sodium: '700mg',
    sugar: '2g',
  },
];
const mockSnack: UIFormattedDailyFoodItem[] = [
  {
    name: 'Greek Yogurt with Berries',
    meal_type: 'snack',
    calories: '200 cal',
    carbs: '30g',
    fat: '3g',
    protein: '15g',
    sodium: '100mg',
    sugar: '20g',
  },
  {
    name: 'Mixed Nuts',
    meal_type: 'snack',
    calories: '250 cal',
    carbs: '15g',
    fat: '20g',
    protein: '5g',
    sodium: '150mg',
    sugar: '2g',
  },
  {
    name: 'Apple Slices with Peanut Butter',
    meal_type: 'snack',
    calories: '300 cal',
    carbs: '40g',
    fat: '10g',
    protein: '7g',
    sodium: '120mg',
    sugar: '30g',
  },
  {
    name: 'Hummus with Carrot Sticks',
    meal_type: 'snack',
    calories: '220 cal',
    carbs: '30g',
    fat: '8g',
    protein: '6g',
    sodium: '180mg',
    sugar: '4g',
  },
  {
    name: 'Dark Chocolate and Almonds',
    meal_type: 'snack',
    calories: '270 cal',
    carbs: '20g',
    fat: '15g',
    protein: '5g',
    sodium: '100mg',
    sugar: '10g',
  },
  {
    name: 'Smoothie with Protein Powder',
    meal_type: 'breakfast',
    calories: '400 cal',
    carbs: '60g',
    fat: '5g',
    protein: '25g',
    sodium: '300mg',
    sugar: '35g',
  },
];

export { mockBreakfast, mockLunch, mockDinner, mockSnack };
