// Generated by Copilot
import { create } from 'zustand';
import { createJSONStorage, persist } from 'zustand/middleware';
import { immer } from 'zustand/middleware/immer';

/**
 * Application theme types
 */
type Theme = 'dark' | 'light' | 'system';

/**
 * App settings state interface
 */
interface AppSettings {
  theme: Theme;
  preferredLanguage: string;
  notifications: boolean;
  analyticsConsent: boolean;
  highPerformanceMode: boolean;
  animationsEnabled: boolean;
}

/**
 * User state interface
 */
interface UserState {
  isAuthenticated: boolean;
  walletAddress: string | null;
  username: string | null;
  profileImage: string | null;
  score: number;
  rank: number | null;
  achievements: string[];
}

/**
 * UI state interface
 */
interface UIState {
  isSidebarOpen: boolean;
  activeModal: string | null;
  toasts: Array<{
    id: string;
    type: 'success' | 'error' | 'info' | 'warning';
    message: string;
    duration?: number;
  }>;
  isLoading: boolean;
}

/**
 * Leaderboard state interface
 */
interface LeaderboardState {
  rankings: Array<{
    walletAddress: string;
    username?: string;
    score: number;
    rank: number;
    profileImage?: string;
  }>;
  timeFrame: 'daily' | 'weekly' | 'monthly' | 'all';
  lastUpdated: string | null;
  isLoading: boolean;
}

/**
 * Complete application state interface
 */
interface AppState {
  // State slices
  settings: AppSettings;
  user: UserState;
  ui: UIState;
  leaderboard: LeaderboardState;

  // Settings actions
  setTheme: (theme: Theme) => void;
  setPreferredLanguage: (language: string) => void;
  toggleNotifications: () => void;
  toggleAnalyticsConsent: () => void;
  toggleHighPerformanceMode: () => void;
  toggleAnimations: () => void;

  // User actions
  setWalletAddress: (address: string | null) => void;
  setUserProfile: (profile: {
    username?: string;
    profileImage?: string;
  }) => void;
  updateUserScore: (score: number) => void;
  addAchievement: (achievement: string) => void;
  logout: () => void;

  // UI actions
  toggleSidebar: () => void;
  openModal: (modalId: string) => void;
  closeModal: () => void;
  addToast: (toast: Omit<UIState['toasts'][0], 'id'>) => string;
  removeToast: (id: string) => void;
  setIsLoading: (isLoading: boolean) => void;

  // Leaderboard actions
  setLeaderboardData: (data: {
    rankings: LeaderboardState['rankings'];
    timeFrame?: LeaderboardState['timeFrame'];
  }) => void;
  setLeaderboardTimeFrame: (timeFrame: LeaderboardState['timeFrame']) => void;
  setLeaderboardLoading: (isLoading: boolean) => void;
}

/**
 * Default settings values
 */
const defaultSettings: AppSettings = {
  theme: 'system',
  preferredLanguage: 'en',
  notifications: true,
  analyticsConsent: false,
  highPerformanceMode: false,
  animationsEnabled: true,
};

/**
 * Default user state
 */
const defaultUserState: UserState = {
  isAuthenticated: false,
  walletAddress: null,
  username: null,
  profileImage: null,
  score: 0,
  rank: null,
  achievements: [],
};

/**
 * Default UI state
 */
const defaultUIState: UIState = {
  isSidebarOpen: false,
  activeModal: null,
  toasts: [],
  isLoading: false,
};

/**
 * Default leaderboard state
 */
const defaultLeaderboardState: LeaderboardState = {
  rankings: [],
  timeFrame: 'all',
  lastUpdated: null,
  isLoading: false,
};

/**
 * Global application store using Zustand with persistence and immer
 * for immutable state updates with type safety
 */
export const useAppStore = create<AppState>()(
  persist(
    immer((set) => ({
      // Initial state
      settings: defaultSettings,
      user: defaultUserState,
      ui: defaultUIState,
      leaderboard: defaultLeaderboardState,

      // Settings actions
      setTheme: (theme) =>
        set((state) => {
          state.settings.theme = theme;
        }),
      setPreferredLanguage: (language) =>
        set((state) => {
          state.settings.preferredLanguage = language;
        }),
      toggleNotifications: () =>
        set((state) => {
          state.settings.notifications = !state.settings.notifications;
        }),
      toggleAnalyticsConsent: () =>
        set((state) => {
          state.settings.analyticsConsent = !state.settings.analyticsConsent;
        }),
      toggleHighPerformanceMode: () =>
        set((state) => {
          state.settings.highPerformanceMode =
            !state.settings.highPerformanceMode;
        }),
      toggleAnimations: () =>
        set((state) => {
          state.settings.animationsEnabled = !state.settings.animationsEnabled;
        }),

      // User actions
      setWalletAddress: (address) =>
        set((state) => {
          if (address) {
            state.user.walletAddress = address;
            state.user.isAuthenticated = true;
          } else {
            state.user.walletAddress = null;
            state.user.isAuthenticated = false;
          }
        }),
      setUserProfile: (profile) =>
        set((state) => {
          if (profile.username) {
            state.user.username = profile.username;
          }
          if (profile.profileImage) {
            state.user.profileImage = profile.profileImage;
          }
        }),
      updateUserScore: (score) =>
        set((state) => {
          state.user.score = score;
        }),
      addAchievement: (achievement) =>
        set((state) => {
          if (!state.user.achievements.includes(achievement)) {
            state.user.achievements.push(achievement);
          }
        }),
      logout: () =>
        set((state) => {
          state.user = { ...defaultUserState };
        }),

      // UI actions
      toggleSidebar: () =>
        set((state) => {
          state.ui.isSidebarOpen = !state.ui.isSidebarOpen;
        }),
      openModal: (modalId) =>
        set((state) => {
          state.ui.activeModal = modalId;
        }),
      closeModal: () =>
        set((state) => {
          state.ui.activeModal = null;
        }),
      addToast: (toast) => {
        const id = `toast-${Date.now()}-${Math.random().toString(36).substring(2, 9)}`;
        set((state) => {
          state.ui.toasts.push({
            id,
            ...toast,
          });
        });

        // Auto-remove toast after specified duration or default 5 seconds
        setTimeout(() => {
          set((state) => {
            state.ui.toasts = state.ui.toasts.filter((t) => t.id !== id);
          });
        }, toast.duration || 5000);

        return id;
      },
      removeToast: (id) =>
        set((state) => {
          state.ui.toasts = state.ui.toasts.filter((toast) => toast.id !== id);
        }),
      setIsLoading: (isLoading) =>
        set((state) => {
          state.ui.isLoading = isLoading;
        }),

      // Leaderboard actions
      setLeaderboardData: ({ rankings, timeFrame }) =>
        set((state) => {
          state.leaderboard.rankings = rankings;
          state.leaderboard.lastUpdated = new Date().toISOString();
          if (timeFrame) {
            state.leaderboard.timeFrame = timeFrame;
          }
        }),
      setLeaderboardTimeFrame: (timeFrame) =>
        set((state) => {
          state.leaderboard.timeFrame = timeFrame;
          // Set loading to true when changing time frame
          state.leaderboard.isLoading = true;
        }),
      setLeaderboardLoading: (isLoading) =>
        set((state) => {
          state.leaderboard.isLoading = isLoading;
        }),
    })),
    {
      name: 'wikiflow-2025-app-state',
      storage: createJSONStorage(() => localStorage),
      // Only persist settings and user state, not UI or leaderboard
      partialize: (state) => ({
        settings: state.settings,
        user: {
          isAuthenticated: state.user.isAuthenticated,
          walletAddress: state.user.walletAddress,
          username: state.user.username,
          profileImage: state.user.profileImage,
          score: state.user.score,
          achievements: state.user.achievements,
        },
      }),
    },
  ),
);

// Selector hooks for specific slices of state
export const useSettings = () => useAppStore((state) => state.settings);
export const useUser = () => useAppStore((state) => state.user);
export const useUI = () => useAppStore((state) => state.ui);
export const useLeaderboard = () => useAppStore((state) => state.leaderboard);

// Action hooks for common operations
export const useTheme = () => {
  const { theme } = useAppStore((state) => state.settings);
  const setTheme = useAppStore((state) => state.setTheme);
  return { theme, setTheme };
};

export const useToasts = () => {
  const toasts = useAppStore((state) => state.ui.toasts);
  const addToast = useAppStore((state) => state.addToast);
  const removeToast = useAppStore((state) => state.removeToast);
  return { toasts, addToast, removeToast };
};

export const useAuth = () => {
  const isAuthenticated = useAppStore((state) => state.user.isAuthenticated);
  const walletAddress = useAppStore((state) => state.user.walletAddress);
  const setWalletAddress = useAppStore((state) => state.setWalletAddress);
  const logout = useAppStore((state) => state.logout);
  return { isAuthenticated, walletAddress, setWalletAddress, logout };
};

export const useModal = () => {
  const activeModal = useAppStore((state) => state.ui.activeModal);
  const openModal = useAppStore((state) => state.openModal);
  const closeModal = useAppStore((state) => state.closeModal);
  return { activeModal, openModal, closeModal };
};

/**
 * Custom hook to access UI state and actions from the global store
 * Returns both UI state and UI actions (toggleSidebar, openModal, closeModal)
 * Generated by Copilot
 */
export function useUIContext() {
  const ui = useAppStore((state) => state.ui);
  const toggleSidebar = useAppStore((state) => state.toggleSidebar);
  const openModal = useAppStore((state) => state.openModal);
  const closeModal = useAppStore((state) => state.closeModal);
  return {
    ...ui,
    toggleSidebar,
    openModal,
    closeModal,
  };
}
